"""Email delivery: SMTP sending and Markdown-to-HTML conversion."""

import smtplib
from datetime import datetime
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

import markdown as md_lib

from .config import EMAIL_CONFIG


def send_email(subject: str, body_text: str, body_html: str = "") -> None:
    """Send the analysis report via SMTP (Gmail App Password recommended)."""
    cfg = EMAIL_CONFIG
    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"]    = cfg["sender_email"]
    msg["To"]      = cfg["recipient_email"]

    msg.attach(MIMEText(body_text, "plain", "utf-8"))
    if body_html:
        msg.attach(MIMEText(body_html, "html", "utf-8"))

    print(f"  [email] Sending to {cfg['recipient_email']} via {cfg['smtp_server']} …")
    with smtplib.SMTP(cfg["smtp_server"], cfg["smtp_port"]) as server:
        server.ehlo()
        server.starttls()
        server.login(cfg["sender_email"], cfg["sender_password"])
        server.sendmail(cfg["sender_email"], cfg["recipient_email"], msg.as_string())
    print("  [email] Sent successfully.")


def report_to_html(md_text: str) -> str:
    """Convert a Markdown report to a styled HTML email body."""
    body = md_lib.markdown(
        md_text,
        extensions=["tables", "fenced_code", "nl2br", "sane_lists", "toc"],
        extension_configs={
            "toc": {"title": "Table of Contents", "toc_depth": "1-3"},
        },
    )
    return f"""<!DOCTYPE html>
<html><head>
<meta charset="utf-8">
<style>
  body       {{ font-family: Arial, sans-serif; max-width: 960px; margin: auto; padding: 24px; color: #222; }}
  h1         {{ color: #1a237e; border-bottom: 2px solid #1a237e; padding-bottom: 6px; }}
  h2         {{ color: #283593; margin-top: 32px; border-bottom: 1px solid #e0e0e0; padding-bottom: 4px; }}
  h3         {{ color: #3949ab; margin-top: 20px; }}
  table      {{ border-collapse: collapse; width: 100%; margin: 16px 0; font-size: 14px; }}
  th         {{ background: #e8eaf6; color: #1a237e; padding: 8px 12px; text-align: left; border: 1px solid #c5cae9; }}
  td         {{ padding: 7px 12px; border: 1px solid #e0e0e0; }}
  tr:nth-child(even) td {{ background: #f5f5f5; }}
  blockquote {{ border-left: 4px solid #7986cb; margin: 12px 0; padding: 8px 16px;
                background: #f3f4fb; border-radius: 0 4px 4px 0; font-size: 1.1em; }}
  code       {{ background: #f5f5f5; padding: 2px 6px; border-radius: 3px;
                font-family: 'Courier New', monospace; font-size: 13px; }}
  pre        {{ background: #263238; color: #eceff1; padding: 14px; border-radius: 6px;
                overflow-x: auto; font-size: 13px; line-height: 1.5; }}
  pre code   {{ background: none; color: inherit; padding: 0; }}
  li         {{ margin: 5px 0; line-height: 1.6; }}
  hr         {{ border: none; border-top: 1px solid #ddd; margin: 24px 0; }}
  p          {{ margin: 8px 0; line-height: 1.7; }}
  a          {{ color: #3949ab; }}
  .footer    {{ font-size: 12px; color: #888; margin-top: 40px;
                border-top: 1px solid #eee; padding-top: 14px; }}
  /* Table of Contents */
  .toc       {{ background: #f3f4fb; border: 1px solid #c5cae9; border-radius: 6px;
                padding: 16px 24px; margin: 16px 0 24px 0; display: inline-block;
                min-width: 260px; max-width: 100%; }}
  .toc .toctitle {{ font-weight: bold; color: #1a237e; font-size: 1em;
                    margin-bottom: 10px; text-transform: uppercase;
                    letter-spacing: 0.05em; }}
  .toc ul    {{ margin: 0; padding-left: 18px; }}
  .toc li    {{ margin: 4px 0; line-height: 1.5; }}
  .toc a     {{ color: #3949ab; text-decoration: none; font-size: 14px; }}
  .toc a:hover {{ text-decoration: underline; }}
  .toc ul ul {{ padding-left: 16px; }}
  .toc ul ul li a {{ color: #5c6bc0; font-size: 13px; }}
  .toc ul ul ul li a {{ color: #7986cb; font-size: 12px; }}
</style>
</head><body>
{body}
<div class="footer">
  Generated by Stock Analysis Tool &nbsp;|&nbsp; Primary sources: BSE India &amp; NSE India
  &nbsp;|&nbsp; {datetime.now().strftime('%d %b %Y %H:%M')} IST
</div>
</body></html>"""
